service: cadastro-pacientes
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
  stage: awslab
  region: us-east-1 

functions:
  listaPacientes:
    handler: handler.listarPacientes  
    events:
      - http:
          path: pacientes
          method: get
  
  obterPacientes:
    handler: handler.obterPacientes  
    events:
      - http:
          path: pacientes/{pacienteId}
          method: get